; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_scripts = external/meshtastic-firmware/bin/platformio-custom.py
extra_configs =
    external/meshtastic-firmware/arch/base.ini
    external/meshtastic-firmware/arch/*/*.ini
    external/meshtastic-firmware/variants/*/platformio.ini


[lib_base]
build_flags = -DAPP_VERSION=lib

#              -Ilib/meshtastic-firmware/src/mesh/generated
#              -Ilib/meshtastic-firmware/src/mesh

#              -Ilib/meshtastic-firmware/src/buzz
#              -Ilib/meshtastic-firmware/src/gps

              -DMESHTASTIC_MINIMIZE_BUILD=1

#              -Ilib/meshtastic-firmware/src/concurrency
              -DUSE_THREAD_NAMES

              -DUSERPREFS_TZ_STRING=tzplaceholder

              -DRADIOLIB_EXCLUDE_CC1101=1
              -DRADIOLIB_EXCLUDE_NRF24=1
              -DRADIOLIB_EXCLUDE_RF69=1
              -DRADIOLIB_EXCLUDE_SX1231=1
              -DRADIOLIB_EXCLUDE_SX1233=1
              -DRADIOLIB_EXCLUDE_SI443X=1
              -DRADIOLIB_EXCLUDE_RFM2X=1
              -DRADIOLIB_EXCLUDE_AFSK=1
              -DRADIOLIB_EXCLUDE_BELL=1
              -DRADIOLIB_EXCLUDE_HELLSCHREIBER=1
              -DRADIOLIB_EXCLUDE_MORSE=1
              -DRADIOLIB_EXCLUDE_RTTY=1
              -DRADIOLIB_EXCLUDE_SSTV=1
              -DRADIOLIB_EXCLUDE_AX25=1
              -DRADIOLIB_EXCLUDE_DIRECT_RECEIVE=1
              -DRADIOLIB_EXCLUDE_BELL=1
              -DRADIOLIB_EXCLUDE_PAGER=1
              -DRADIOLIB_EXCLUDE_FSK4=1
              -DRADIOLIB_EXCLUDE_APRS=1
              -DRADIOLIB_EXCLUDE_LORAWAN=1

              -DMESHTASTIC_EXCLUDE_DROPZONE=1
              -DMESHTASTIC_EXCLUDE_REMOTEHARDWARE=1
              -DMESHTASTIC_EXCLUDE_HEALTH_TELEMETRY=1
              -DMESHTASTIC_EXCLUDE_POWERSTRESS=1 ; exclude power stress test module from main firmware
              -DMESHTASTIC_EXCLUDE_GPS=1

              -DHAS_TELEMETRY=0


lib_deps =
    ${radiolib_base.lib_deps}
;    nanopb/Nanopb@0.4.9
    MeshtasticProto
    erriez/ErriezCRC32@1.0.1

[arduino_lib]
build_flags = ${lib_base.build_flags}
lib_deps =
    ${lib_base.lib_deps}
    ${arduino_base.lib_deps}
    https://github.com/meshtastic/ArduinoThread.git#1ae8778c85d0a2a729f989e0b1e7d7c4dc84eef0
    mathertel/OneButton@2.6.1
    https://github.com/meshtastic/arduino-fsm.git#7db3702bf0cfe97b783d6c72595e3f38e0b19159
    https://github.com/meshtastic/esp8266-oled-ssd1306.git#e16cee124fe26490cb14880c679321ad8ac89c95



[esp32_base_lib]
extends = esp32_base
board_build.partitions =

build_flags = ${arduino_lib.build_flags}
    -Iexternal/meshtastic-firmware/src/platform/esp32
lib_deps = ${arduino_lib.lib_deps}
           rweather/Crypto@^0.4.0
           https://github.com/meshtastic/esp32_https_server.git#23665b3adc080a311dcbb586ed5941b5f94d6ea2


[esp32s3_base_lib]
extends = esp32_base_lib
custom_esp32_kind = esp32s3



[env:heltec_lib]
extends = esp32s3_base_lib
board = heltec_wifi_lora_32_V3
board_check = true
# Temporary until espressif creates a release with this new target
build_flags =
    ${arduino_lib.build_flags} ${esp32s3_base_lib.build_flags} -D HELTEC_V3 -I external/meshtastic-firmware/variants/heltec_v3
    -DGPS_POWER_TOGGLE ; comment this line to disable triple press function on the user button to turn off gps entirely.


lib_ignore = MeshtasticFirmware
#lib_ignore = mesh

build_src_filter =
    ${arduino_base.build_src_filter}
#    -<platform/nrf52/> -<platform/stm32wl> -<platform/rp2xx0> -<mesh/eth/> -<mesh/raspihttp>
#    -<lib/meshtastic-firmware/src/platform/nrf52/> -<lib/meshtastic-firmware/src/platform/stm32wl> -<lib/meshtastic-firmware/src/platform/rp2xx0> -<lib/meshtastic-firmware/src/mesh/eth/> -<lib/meshtastic-firmware/src/mesh/raspihttp>


upload_port = /dev/cu.usbserial-4
monitor_port = /dev/cu.usbserial-4